name: ${pluginname}
description: ${description}
author: Hadde
version: ${version}
main: de.eldoria.pickmeup.PickMeUp
website: ${url}
api-version: 1.13
softdepend:
  - BentoBox

commands:
  pickmeup:
    description: main command of pick me up
    usage: trust the tab completion
    aliases:
      - pmu
